---
name: pull_request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         python-version: [3.7]
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
